services:
  descarregar:
    build:
      context: $PWD
      dockerfile: $PWD/Dockerfile
    restart: on-failure
    volumes:
      - $PWD/downloads:/tmp/downloads
    ports:
      - ${DECARREGAR_PORT}:5000
    environment:
      CSV_FILE_PATH: ${CSV_FILE_PATH}
      SITE: ${SITE}
      LOGIN: ${LOGIN}
      RESPONSE_URL: ${RESPONSE_URL}
      USER_EMAIL: ${USER_EMAIL}
      USER_PASSWORD: ${USER_PASSWORD}
